import re

# List of (regular expression, replacement) pairs for abbreviations in swedish:
abbreviations_sv = [
    (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
    for x in [
        ("mkr", "miljoner"),
        ("milj", "miljoner"),
        ("mdr", "miljarder"),
        ("proc", "procent"),
        ("kr", "kronor"),
        ("1:a", "första"),
        ("2:a", "andra"),
        ("2:e", "andra"),
        ("3:e", "tredje"),
        ("4:e", "fjärde"),
        ("4:o", "fjärde"),
        ("5:e", "femte"),
        ("6:e", "sjätte"),
        ("7:e", "sjunde"),
        ("8:e", "åttonde"),
        ("8:o", "åttonde"),
        ("9:e", "nionde"),
        ("10:e", "tionde"),
        ("11:e", "elfte"),
        ("12:e", "tolfte"),
        ("12:o", "tolfte"),
        ("13:e", "trettonde"),
        ("14:e", "fjortonde"),
        ("obs", "observera"),
        ("dvs", "det vill säga"),
        ("mao", "med andra ord"),
        ("d.v.s.", "det vill säga"),
        ("m.a.o.", "med andra ord"),
        ("iofs", "i och för sig"),
        ("el", "eller"),        
        ("t.ex", "till exempel"),        
        ("fig", "figur"),        
        ("ev", "eventuellt"),        
        ("pga", "på grund av"),        
        ("v.", "vecka"),        
        ("s.k", "så kallad"),        
        ("ab", "aktiebolag"),        
        ("m.m", "med mera"),        
        ("m.fl", "med flera"),
        ("osv", "och så vidare"),
        ("etc", "et cetera"),
        ("f.ö", "för övrigt"),
        ("ang", "angående"),
        ("ung", "ungefär"),
        ("f.kr", "före kristus"),
        ("e.kr", "efter kristus"),
        ("jfr", "jämför"),
        ("f.d", "före detta"),
        ("mvh", "med vänliga hälsningar"),
        ("kl", "klockan"),
        ("bl.a", "bland annat"),
        ("t.o.m", "till och med"),
        ("fr.o.m", "från och med"),
        ("s.", "sidan"),
        ("anm.", "anmärkning"),
        ("ca.", "cirka"),
        ("dr.", "doktor"),
        ("fam.", "familj"),
        ("fast.", "fastighet"),
        ("forts.", "fortsättning"),
        ("frånv.", "frånvarande"),
        ("jfr.", "jungfru"),
        ("mån.", "månad"),
    ]
]
